# Generated by Django 3.1.12 on 2024-11-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20241120_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapefiledata',
            name='geometry',
        ),
    ]
