# Generated by Django 3.2 on 2024-11-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20241121_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleData',
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
