# Generated by Django 3.2 on 2024-11-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20241122_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
    ]
